# print('a'.isidentifier())
# print(''.isidentifier())
# print('_'.isidentifier())
# print('9ty'.isidentifier())
# print('hello world'.isidentifier())
# print('hello_world'.isidentifier())
# print('78is mine'.isidentifier())
# print('hello9world'.isidentifier())

# print('   '.isspace())
# print('hello world'.isspace())
# print('       _'.isspace())
# print(''.isspace())
# print(' hi '.isspace())
# print('948504   '.isspace())
# print('@siejoi'.isspace())

# print(isinstance(7,int))
# print(isinstance(7,float))
# print(isinstance(7,str))
# print(isinstance('hello', str))
# print(isinstance('hello', int))
# print(isinstance('hello', float))
# print(isinstance(7.8,float))
# print(isinstance(7.8,int))
# print(isinstance(7.8,str))

# print('hola'.isalpha())
# print('ho_la'.isalpha())
# print('ho  la'.isalpha())
# print('ho9la'.isalpha())

# print('4849043'.isalnum())
# print('FJDFDID'.isalnum())
# print('4857.454'.isalnum())
# print('h9ty'.isalnum())
# print('@48%$%'.isalnum())

print('hellopython'.find('o')) 
print('hellopython'.find('o', 6)) 
print('hellopython'.find('o' ,2)) 
print('hellopython'.find('h' ,5)) 